// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCNEXTCoreApp.Data.Master;

namespace SCNEXTCoreApp.Migrations
{
    [DbContext(typeof(GeneralDbContext))]
    [Migration("20191121121402_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressAprtNo")
                        .HasMaxLength(50);

                    b.Property<string>("AddressAreaCode")
                        .HasMaxLength(50);

                    b.Property<string>("AddressAreaName")
                        .HasMaxLength(50);

                    b.Property<string>("AddressBuildingName")
                        .HasMaxLength(50);

                    b.Property<string>("AddressBuildingNo")
                        .HasMaxLength(50);

                    b.Property<string>("AddressCity")
                        .HasMaxLength(50);

                    b.Property<string>("AddressClosestLandMark")
                        .HasMaxLength(50);

                    b.Property<string>("AddressContactNo1")
                        .HasMaxLength(50);

                    b.Property<string>("AddressContactNo2")
                        .HasMaxLength(50);

                    b.Property<string>("AddressContactPerson1")
                        .HasMaxLength(50);

                    b.Property<string>("AddressContactPerson2")
                        .HasMaxLength(50);

                    b.Property<string>("AddressCountry")
                        .HasMaxLength(50);

                    b.Property<string>("AddressDistrict")
                        .HasMaxLength(50);

                    b.Property<string>("AddressEmailId1")
                        .HasMaxLength(50);

                    b.Property<string>("AddressEmailId2")
                        .HasMaxLength(50);

                    b.Property<string>("AddressField1")
                        .HasMaxLength(50);

                    b.Property<string>("AddressField2")
                        .HasMaxLength(50);

                    b.Property<string>("AddressField3")
                        .HasMaxLength(50);

                    b.Property<string>("AddressField4")
                        .HasMaxLength(50);

                    b.Property<string>("AddressField5")
                        .HasMaxLength(50);

                    b.Property<string>("AddressFloorNo")
                        .HasMaxLength(50);

                    b.Property<string>("AddressLatLoc")
                        .HasMaxLength(50);

                    b.Property<string>("AddressLongLoc")
                        .HasMaxLength(50);

                    b.Property<string>("AddressState")
                        .HasMaxLength(50);

                    b.Property<string>("AddressStreetName")
                        .HasMaxLength(50);

                    b.Property<string>("AddressStreetNo")
                        .HasMaxLength(50);

                    b.Property<string>("AddressUrl")
                        .HasMaxLength(250);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<int>("TypeId");

                    b.Property<int>("TypeRefId");

                    b.HasKey("AddressId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandCode")
                        .HasMaxLength(30);

                    b.Property<string>("BrandName")
                        .HasMaxLength(100);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<int>("MfrId");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("BrandId");

                    b.ToTable("brand");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityCode")
                        .HasMaxLength(10);

                    b.Property<string>("CityName")
                        .HasMaxLength(80);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<int>("CountryId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("StateId");

                    b.Property<int>("Status");

                    b.HasKey("CityId");

                    b.ToTable("city");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.CompanyDet", b =>
                {
                    b.Property<int>("CmpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId");

                    b.Property<DateTime>("CmpTimeZone");

                    b.Property<string>("CompAddress")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("CompAddress2")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("CompAltPhoneNo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CompBussinessHr");

                    b.Property<int>("CompCity");

                    b.Property<string>("CompCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CompContactName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CompCountry");

                    b.Property<int>("CompLoginEnable");

                    b.Property<string>("CompName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("CompPrefPhoneNo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CompRefNameNo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("CompState");

                    b.Property<string>("CompTrnNo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CompZipCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("CompanyID")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("CountryId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("DefWorkEndTime");

                    b.Property<DateTime>("DefWorkStartTime");

                    b.Property<DateTime>("FinEndDate");

                    b.Property<DateTime>("FinStartDate");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<int>("LicenseType");

                    b.Property<string>("Logo")
                        .HasMaxLength(150);

                    b.Property<DateTime>("MaxWrkHr");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("OrgID")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("OrgTypeID");

                    b.Property<int?>("StateId");

                    b.Property<int>("Status");

                    b.Property<string>("TrnNo")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("UserLimit");

                    b.Property<string>("compLogo")
                        .HasMaxLength(150);

                    b.HasKey("CmpId");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("StateId");

                    b.ToTable("CompanyDet");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10);

                    b.Property<string>("CountryName")
                        .HasMaxLength(80);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("callingCode")
                        .HasMaxLength(8);

                    b.HasKey("CountryId");

                    b.ToTable("country");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Currency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("CurrencyId");

                    b.ToTable("currency");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CustCode")
                        .HasMaxLength(50);

                    b.Property<int>("CustLoginEnable");

                    b.Property<string>("CustName")
                        .HasMaxLength(200);

                    b.Property<string>("CustTrnNo")
                        .HasMaxLength(50);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("CustId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("DeptId");

                    b.ToTable("department");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.DgClassDangerous", b =>
                {
                    b.Property<int>("DgClassDangerousId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("DgClassDangerousCode")
                        .HasMaxLength(10);

                    b.Property<string>("DgClassDangerousDescription")
                        .HasMaxLength(150);

                    b.Property<string>("DgClassDangerousName")
                        .HasMaxLength(80);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("DgClassDangerousId");

                    b.ToTable("DgClassDangerous");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.EmpSkillSet", b =>
                {
                    b.Property<int>("EmpSkillSetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("EmpSkillSetCode")
                        .HasMaxLength(30);

                    b.Property<string>("EmpSkillSetName")
                        .HasMaxLength(100);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("EmpSkillSetId");

                    b.ToTable("EmpSkillSet");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(100);

                    b.Property<decimal>("BasicSalary");

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CityId");

                    b.Property<string>("CompanyEmail")
                        .HasMaxLength(50);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("ContactNo")
                        .HasMaxLength(50);

                    b.Property<int>("CountryId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("CurrencyId");

                    b.Property<DateTime>("DOB");

                    b.Property<DateTime>("DOJ");

                    b.Property<DateTime>("DateofRelieve");

                    b.Property<DateTime>("DateofResign");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("Designation")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("EmergencyNo")
                        .HasMaxLength(100);

                    b.Property<string>("EmiratesId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(30);

                    b.Property<string>("EmpDirectStatus");

                    b.Property<DateTime>("EmpEndDate");

                    b.Property<string>("EmpFirstName")
                        .HasMaxLength(100);

                    b.Property<string>("EmpIndirectSupID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpLastName")
                        .HasMaxLength(100);

                    b.Property<string>("EmpMiddleName")
                        .HasMaxLength(100);

                    b.Property<DateTime>("EmpStartDate");

                    b.Property<string>("ExpatNo")
                        .HasMaxLength(100);

                    b.Property<string>("Extension");

                    b.Property<string>("FaxNo")
                        .HasMaxLength(100);

                    b.Property<string>("Gender")
                        .HasMaxLength(10);

                    b.Property<decimal>("HRAAmt");

                    b.Property<string>("HomeLandNo")
                        .HasMaxLength(100);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("IdentificationDocID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(150);

                    b.Property<string>("InsCardNo")
                        .HasMaxLength(100);

                    b.Property<DateTime>("InsExpDate");

                    b.Property<string>("InsProviderID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandlineNo")
                        .HasMaxLength(100);

                    b.Property<int>("LanguageId");

                    b.Property<DateTime>("LastAnnualLeave");

                    b.Property<DateTime>("LicExpiryDate");

                    b.Property<DateTime>("LicIssueDate");

                    b.Property<string>("LicenseIssuePlace")
                        .HasMaxLength(100);

                    b.Property<string>("LicenseNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseType");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("NationalityID");

                    b.Property<decimal>("OtherAllowanceAmt");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(100);

                    b.Property<string>("PlaceOfIssue")
                        .HasMaxLength(100);

                    b.Property<string>("PostCode");

                    b.Property<string>("Profession")
                        .HasMaxLength(100);

                    b.Property<string>("RepToMangr");

                    b.Property<int>("StateId");

                    b.Property<int>("Status");

                    b.Property<decimal>("TransportAmt");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("VisaExpDate");

                    b.Property<DateTime>("VisaIssueDate");

                    b.Property<string>("VisaNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VisaStatus")
                        .HasMaxLength(100);

                    b.Property<string>("Weburl");

                    b.Property<int>("YearOfexp");

                    b.HasKey("EmpId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.HSCode", b =>
                {
                    b.Property<int>("HSCodeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("HSCodeId");

                    b.ToTable("HSCode");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.JobStatus", b =>
                {
                    b.Property<int>("JobStatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("JobStatCode")
                        .HasMaxLength(30);

                    b.Property<string>("JobStatName")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("JobStatId");

                    b.ToTable("jobStatus");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Manufacturer", b =>
                {
                    b.Property<int>("MfrId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("MfrCode")
                        .HasMaxLength(30);

                    b.Property<string>("MfrName")
                        .HasMaxLength(100);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.HasKey("MfrId");

                    b.ToTable("manufacturer");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.OUType", b =>
                {
                    b.Property<int>("OUTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("OUTypeID");

                    b.ToTable("OUType");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.ReOrderingFlowFreq", b =>
                {
                    b.Property<int>("ReOrderingFlowFreqId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("ReOrderingFlowFreqCode")
                        .HasMaxLength(10);

                    b.Property<string>("ReOrderingFlowFreqDescription")
                        .HasMaxLength(150);

                    b.Property<string>("ReOrderingFlowFreqName")
                        .HasMaxLength(80);

                    b.Property<int>("Status");

                    b.HasKey("ReOrderingFlowFreqId");

                    b.ToTable("ReOrderingFlowFreq");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<int>("CountryId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("StateCode")
                        .HasMaxLength(10);

                    b.Property<string>("StateName")
                        .HasMaxLength(80);

                    b.Property<int>("Status");

                    b.HasKey("StateId");

                    b.ToTable("state");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Supplier", b =>
                {
                    b.Property<int>("SupID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("SupCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SupLoginEnable")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SupName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SupTrnNo")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SupID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Uom", b =>
                {
                    b.Property<int>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("UomId");

                    b.ToTable("Uom");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehBrand", b =>
                {
                    b.Property<int>("VehBrandId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehBrandCode")
                        .HasMaxLength(10);

                    b.Property<string>("VehBrandName")
                        .HasMaxLength(80);

                    b.HasKey("VehBrandId");

                    b.ToTable("VehBrand");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehGearType", b =>
                {
                    b.Property<int>("VehGearTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehGearTypeCode")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("VehGearTypeName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("VehGearTypeId");

                    b.ToTable("VehGearType");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehMake", b =>
                {
                    b.Property<int>("VehMakeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehMakeCode")
                        .HasMaxLength(10);

                    b.Property<string>("VehMakeName")
                        .HasMaxLength(80);

                    b.HasKey("VehMakeId");

                    b.ToTable("VehMake");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehOwnrType", b =>
                {
                    b.Property<int>("VehOwnrTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehOwnrTypeCode")
                        .HasMaxLength(30);

                    b.Property<string>("VehOwnrTypeName")
                        .HasMaxLength(100);

                    b.HasKey("VehOwnrTypeId");

                    b.ToTable("VehOwnrType");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehPermit", b =>
                {
                    b.Property<int>("VehPermitId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehPermitName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("VehPermitId");

                    b.ToTable("VehPermit");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehPlatePrefix", b =>
                {
                    b.Property<int>("VehPlatePrefixId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehPlatePrefixCode")
                        .HasMaxLength(10);

                    b.Property<string>("VehPlatePrefixName")
                        .HasMaxLength(80);

                    b.HasKey("VehPlatePrefixId");

                    b.ToTable("VehPlatePrefix");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.VehicleLicenceType", b =>
                {
                    b.Property<int>("VehLicTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<int>("Status");

                    b.Property<string>("VehLicTypeCode")
                        .HasMaxLength(30);

                    b.Property<string>("VehLicTypeName")
                        .HasMaxLength(100);

                    b.HasKey("VehLicTypeId");

                    b.ToTable("vehicleLicenceType");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Vehicletype", b =>
                {
                    b.Property<int>("VehtypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("VehtypeId");

                    b.ToTable("vehicletype");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("BranchId");

                    b.Property<int>("CityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("ContPerEmail")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("ContPerMobNo")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("ContactPer")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("CountryId");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int?>("CurrencyId");

                    b.Property<int?>("DepartmentDeptId");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<int>("MangerID");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("StateId");

                    b.Property<int>("Status");

                    b.Property<int>("WMCurrencyId");

                    b.Property<int>("WMDepartmentId");

                    b.Property<string>("WMEmail")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("WMFaxNo")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("WMTeleNo")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("WMUrl")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("WarehouseId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("DepartmentDeptId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.binarea", b =>
                {
                    b.Property<int>("binId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BinName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<int>("IsAc");

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("Status");

                    b.Property<int>("WarehouseId");

                    b.HasKey("binId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("binarea");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.pimcategory", b =>
                {
                    b.Property<int>("PimCatID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("VatStatus");

                    b.Property<int>("VatType");

                    b.HasKey("PimCatID");

                    b.ToTable("pimcategory");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.pimcategorytype", b =>
                {
                    b.Property<int>("PimCatTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("PimCatID");

                    b.Property<int>("Status");

                    b.Property<int>("VatStatus");

                    b.Property<int>("VatType");

                    b.HasKey("PimCatTypeID");

                    b.HasIndex("PimCatID");

                    b.ToTable("pimcategorytype");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.taxmaster", b =>
                {
                    b.Property<int>("TaxId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<double>("Rate")
                        .HasMaxLength(150);

                    b.Property<int>("Status");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("TaxId");

                    b.ToTable("taxmaster");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.vehowner", b =>
                {
                    b.Property<int>("VehOwnerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("CompanyID")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("IP")
                        .HasMaxLength(50);

                    b.Property<string>("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("Status");

                    b.HasKey("VehOwnerId");

                    b.ToTable("vehowner");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.CompanyDet", b =>
                {
                    b.HasOne("SCNEXTCoreApp.Models.Master.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("SCNEXTCoreApp.Models.Master.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("SCNEXTCoreApp.Models.Master.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.Warehouse", b =>
                {
                    b.HasOne("SCNEXTCoreApp.Models.Master.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("SCNEXTCoreApp.Models.Master.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentDeptId");
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.binarea", b =>
                {
                    b.HasOne("SCNEXTCoreApp.Models.Master.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SCNEXTCoreApp.Models.Master.pimcategorytype", b =>
                {
                    b.HasOne("SCNEXTCoreApp.Models.Master.pimcategory", "pimcategory")
                        .WithMany()
                        .HasForeignKey("PimCatID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
